
services:
  server:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 8787:8787
    depends_on:
      - db
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8181:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Sjef
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  frontend:
    image: node:alpine
    build:
      context: ./frontend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    depends_on:
      - server

volumes:
  db-data:


# Here you can define your secrets. Secrets are used to pass sensitive
#   db-password:
#     file: db/password.txt

