
services:

  server:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 8787:8787
    depends_on:
      - db
  
  
  db:
    image: postgres:16
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  frontend:
    image: node:alpine
    build:
      context: ./frontend
    ports:
      - 5173:5173
    environment:
      NODE_ENV: production
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  db-data:


# Here you can define your secrets. Secrets are used to pass sensitive
#   db-password:
#     file: db/password.txt

