version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Running locally for dev so i can hot reload
  # backend:
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - 8787:8787
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev
  #   depends_on:
  #     - db

  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - 5173:5173
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev
  #   depends_on:
  #     - backend
    


volumes:
  db-data: